### ISSUE TITLE
original select seems not to be affected from clone selection

### ISSUE THREAD

**Issue by stratboy** [mikemaccana/styleselect#14]
Hi, on your website, if I select your example and take a look at the source hidden select, I can see selection there is still option 2 (your default) and not my own.

**Comment by breadadams** [comment]
@stratboy the `selected` attribute will still appear on the `<option value="value2"...` as that's just for setting the `<select>`'s initial value, but if you check its `.value` in the console, you'll see that contains the correct value you've updated to, eg:

![image](https://user-images.githubusercontent.com/5795227/33274929-bd016e48-d391-11e7-94e9-85711b434f8a.png)

**Comment by mikemaccana** [comment]
Thanks @breadadams! 🙂
