### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by hamsterbacke23** [mikemaccana/styleselect#3]
Right now IE9 creates problems because of the missin bind() function
Maybe use the bind polyfill from here?
 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

**Comment by tim-bezhashvyly** [comment]
In my opinion it will be cleaner not to use aliases.

**Comment by mikemaccana** [comment]
I don't think anyone cares about IE, much less IE9 in 2017. Those that do can add a polyfill.
